p = [...
     'C:\MATLAB\StartHere\ann_wrapper;', ...
     'C:\MATLAB\StartHere\MatlabFns;',...
     'C:\MATLAB\StartHere\vlfeat-0.9.17;',...   
     'C:\MATLAB\StartHere\SVT_MostRecent;',...
     'C:\MATLAB\StartHere\Apps;',...
     'C:\MATLAB\StartHere\export_fig;',...
     'C:\MATLAB\StartHere\SupportFns;',...      
     'C:\MATLAB\StartHere\MyFuncs;',...
     'C:\MATLAB\StartHere\GCMex;',...
];
addpath(p)
disp('vl_setup')
run ('C:\MATLAB\StartHere\vlfeat-0.9.17\toolbox\vl_setup')
disp('Aproximate Nearest Neighbourhood Setup')
run ('C:\MATLAB\StartHere\ann_wrapper\ann_class_compile')
opengl software
format ShortG